service: okta-domains

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-jest-plugin
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api-${self:provider.stage}.idp.rocks
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: false
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
    stages:
      - dev
      - test
  jest:
    # You can pass jest options here
    # See details here: https://facebook.github.io/jest/docs/configuration.html
    # For instance, uncomment next line to enable code coverage
    collectCoverage: true

provider:
  name: aws
  runtime: nodejs12.x
  profile: udp-admin
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  timeout: 5
  environment:
    DNS_VERIFY_PREFIX: _oktadac.verification
    DOMAINS_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    VERIFICATIONS_TABLE: ${self:service}-verify-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DOMAINS_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DOMAINS_TABLE}/index/*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.VERIFICATIONS_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.VERIFICATIONS_TABLE}/index/*"

functions:
  addDomain:
    handler: domains/create.handler
    events:
      - http:
          path: domains
          method: post
          cors: true

  # verifyDomain:
  #   handler: domains/update.handler
  #   events:
  #     - http:
  #         path: domains/{name}/verify
  #         method: put
  #         cors: true

  getDomain:
    handler: domains/get.handler
    events:
      - http:
          path: domains/{domain}
          method: get
          cors: true

  removeDomain:
    handler: domains/delete.handler
    events:
      - http:
          path: domains/{domain}
          method: delete
          cors: true

  listDomains:
    handler: domains/list.handler
    events:
      - http:
          path: domains
          method: get
          cors: true

  webfinger:
    handler: domains/webfinger.handler
    events:
      - http:
          path: .well-known/webfinger
          method: get
          cors: true

  createVerification:
    handler: verifications/create.handler
    events:
      - http:
          path: verifications
          method: post
          cors: true

  checkVerification:
    handler: verifications/verify.handler
    events:
      - http:
          path: verifications/{domain}
          method: put
          cors: true

  getVerification:
    handler: verifications/get.handler
    events:
      - http:
          path: verifications/{domain}
          method: get
          cors: true

  deleteVerification:
    handler: verifications/delete.handler
    events:
      - http:
          path: verifications/{domain}
          method: delete
          cors: true

resources:
  Resources:
    VerificationsDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.VERIFICATIONS_TABLE}
        AttributeDefinitions:
          - AttributeName: domain
            AttributeType: S
          - AttributeName: idp
            AttributeType: S
        KeySchema:
          - AttributeName: idp
            KeyType: HASH
          - AttributeName: domain
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: idps-${self:provider.environment.DOMAINS_TABLE}
            KeySchema:
              - AttributeName: idp
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - domain
                - tenant
                - created
                - updated
                - verified
                - dnsVerificationString
              ProjectionType: INCLUDE
          - IndexName: domains-${self:provider.environment.VERIFICATIONS_TABLE}
            KeySchema:
              - AttributeName: domain
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - idp
                - tenant
                - created
                - updated
                - verified
                - dnsVerificationString
              ProjectionType: INCLUDE
        BillingMode: PAY_PER_REQUEST
    DomainsDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DOMAINS_TABLE}
        AttributeDefinitions:
          - AttributeName: domain
            AttributeType: S
          - AttributeName: idp
            AttributeType: S
        KeySchema:
          - AttributeName: idp
            KeyType: HASH
          - AttributeName: domain
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: idps-${self:provider.environment.DOMAINS_TABLE}
            KeySchema:
              - AttributeName: idp
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - domain
                - created
                - verified
              ProjectionType: INCLUDE
          - IndexName: domains-${self:provider.environment.DOMAINS_TABLE}
            KeySchema:
              - AttributeName: domain
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - idp
                - created
                - verified
              ProjectionType: INCLUDE
        BillingMode: PAY_PER_REQUEST
